### ISSUE TITLE
添加到主题的代码不对

### ISSUE THREAD

**Issue by enouch** [EYHN/hexo-helper-live2d#1]
文件是 /layout/_layout.swig
修改的代码：
<canvas id="live2dcanvas" width="300" height="600" class="live2d"></canvas>
                <script type="text/javascript" src="/live2d/script"></script><script type="text/javascript">live2dStart("live2dcanvas","/live2d/z16/z16.model.json");</script>
                <style>
                .live2d{
                    position: fixed;
                    bottom: -30px;
                    right: 0px;
                    z-index: 999;
                    width: 150px;
                    height: 300px;
                    pointer-events: none
                }
                </style>

**Comment by EYHN** [comment]
不同的模版语言对应的调用方式不同
