### ISSUE TITLE
使用问题

### ISSUE THREAD

**Issue by Ma5ker** [EYHN/hexo-helper-live2d#103]
为什么我添加后本地预览出现live2d tag was deprecated since 3.0. See #36. PLEASE REMOVE live2d TAG IN YOUR TEMPLATE FILE.
 npm install --save hexo-helper-live2d@3.x执行后显示：

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
+ hexo-helper-live2d@3.0.2
updated 1 package in 9.073s

然后本地预览出现：
INFO  Start processing
INFO  Hexo is running at http://localhost:4000/. Press Ctrl+C to stop.
INFO  HEXO-HELPER-LIVE2D: live2d tag was deprecated since 3.0. See #36. PLEASE REMOVE live2d TAG IN YOUR TEMPLATE FILE.
INFO  HEXO-HELPER-LIVE2D: live2d tag was deprecated since 3.0. See #36. PLEASE REMOVE live2d TAG IN YOUR TEMPLATE FILE.
浏览网页发现没有加载

**Comment by Ma5ker** [comment]
em…… 好像部署后又是可以的，很奇怪

**Comment by Yggdrasill-7C9** [comment]
我这里也是很奇怪，_config.yml 把所有 live2d 的参数注释掉看板娘就粗线了，把所有live2d 的参数加上看板娘就消失了

**Comment by Ma5ker** [comment]
em……不好意思，我昨天试了几次，终于知道了，现在的版本不用额外在在layout里面加入live2d的tag了，我参看的教程貌似都没改过来，现在直接在配置文件加入就行了，谢谢作者，插件很可爱，很好用：）
