### ISSUE TITLE
用npm安装后网站的lunr用不了了。

### ISSUE THREAD

**Issue by zhangao4833** [EYHN/hexo-helper-live2d#105]
# Issue

### Steps to reproduce the behavior 复现步骤

- [ ] I have alreday read instructions in [CONTRIBUTING](./CONTRIBUTING.md).
  我已仔细阅读[CONTRIBUTING](./CONTRIBUTING.md)中的相关内容。

> Change the `[ ]` into `[x]` to show your acceptance.
将 `[ ]` 变为 `[x]` 来表示你接受了这些问题。

@EYHN @xiazeyu

**Comment by xiazeyu** [comment]
能否提供详细信息?
如网站地址，控制台输出，其他异常表现？

**Comment by zhangao4833** [comment]
![yzgojf go0s5zhi id nxf](https://user-images.githubusercontent.com/31695433/39427733-79838d50-4cb7-11e8-9e21-318042207230.png)

**Comment by zhangao4833** [comment]
npm install --save hexo-helper-live2d
执行了这条安装  后就这样了

**Comment by xiazeyu** [comment]
npm uninstall hexo-helper-live2d --save后能恢复吗?

**Comment by xiazeyu** [comment]
我大概看了一下，应该是lunr这个库没有安装成功..大概不是我们插件的锅。
你试试
npm install --save lunr

https://github.com/Mrminfive/hexo-theme-skapp/blob/415de852a03eb24c3c3cbf8b2b5d47f031a61ee9/scripts/renderer.js#L5

**Comment by zhangao4833** [comment]
但是执行了  npm uninstall hexo-helper-live2d --save  后就正常了啊

**Comment by xiazeyu** [comment]
https://github.com/Mrminfive/hexo-theme-skapp/blob/72bad0d1f9afac111fbd78fe0bab229f8f446aff/README.md#how-to-use
作者说在Windows上安装可能会踩坑。
要不您重新安装一下依赖，然后看看有没有什么WARN之类的?

**Comment by zhangao4833** [comment]
我试试重新安装下依赖，他依赖有点多，你等会

**Comment by xiazeyu** [comment]
你的截图里只有找不到lunr的报错，我看了一下npm上找不到mamboer/lunr.js，只有https://www.npmjs.com/search?q=lur.js&csrftoken=Oz-rJcD8Qc8bYKRi9mcpxBMljPsjIxw9p3DLTxBuQ5L
和mambo

**Comment by zhangao4833** [comment]
![z 4wtshp7e wru1 996f1hw](https://user-images.githubusercontent.com/31695433/39428390-c2ac6a7c-4cb9-11e8-8ad5-4787f865ded6.png)
但是  执行卸载 npm uninstall hexo-helper-live2d --save  就恢复了  
是不是有冲突啊

**Comment by zhangao4833** [comment]
![1e4fz3m8 c 0o4 vd 6kzbw](https://user-images.githubusercontent.com/31695433/39428447-f06379a6-4cb9-11e8-861a-4ad5893c4e67.png)
这是 重新安装依赖后的   有 5 个WARN

**Comment by xiazeyu** [comment]
我也不知道卸载以后发生了什么..
我只能根据你提供的log作出判断..
看起来是renderer.js的问题，而且错误堆栈里没有live2d相关的东西...
(这次看起来不像hexo的锅)
你试试单独安装lunr?

**Comment by xiazeyu** [comment]
我怀疑卸载hexo-helper-live2d后那个renderer.js根本没被加载..

**Comment by xiazeyu** [comment]
hexo clean
hexo g --debug
试试

**Comment by xiazeyu** [comment]
npm install --save mamboer/lunr.js

**Comment by zhangao4833** [comment]
![ln dk0p _iw6gyxh e](https://user-images.githubusercontent.com/31695433/39428705-f30b359e-4cba-11e8-85f8-7e111401f9fe.png)

这是单独安装 lunr的
![bdo oif8bsb17sbpl y a8m](https://user-images.githubusercontent.com/31695433/39428888-9dbcdf7e-4cbb-11e8-945e-f1c85c072fe3.png)

这是debug里面的   这个文件加载了啊

**Comment by zhangao4833** [comment]
日志中我还看到了 lunr.min.js 说明 lunr也是正常的啊

**Comment by zhangao4833** [comment]
感觉应该是和 node_modules  文件夹 里面的东西有关 是不是 由于安装了这个  改了 某些文件的 路径 导致的啊

**Comment by zhangao4833** [comment]
![kf9hsuc6 x rvox o _ o5h](https://user-images.githubusercontent.com/31695433/39429540-bb6d56f0-4cbd-11e8-9a0f-e6d9410b7b51.png)
 这个是他的 全部 错误  后面的 基本都是在  node_modules 文件夹中

**Comment by xiazeyu** [comment]
"dependencies": {
    "colors": "^1.2.1",
    "hexo-fs": "^0.2.2",
    "hexo-log": "^0.2.0",
    "live2d-widget": "^3.0.5",
    "lodash": "^4.17.5",
    "path": "^0.12.7"
  },

package-lock.json是记录依赖的
目前3.0版本的依赖如上
要不您在仔细排除一下问题?
有新的发现请回复.

**Comment by zhangao4833** [comment]
![u0 kk3uca4ak uc4t0u58zq](https://user-images.githubusercontent.com/31695433/39460254-a64416e8-4d34-11e8-945e-f95b44bebf7a.png)
![rd5 3 o n8lo7r d 5 tre](https://user-images.githubusercontent.com/31695433/39460255-a68fe410-4d34-11e8-981b-8ff15f6177a4.png)
![yvkca w38 o 7o y 4l 0](https://user-images.githubusercontent.com/31695433/39460256-a6c955b0-4d34-11e8-9b56-895a37c74268.png)
![vnj64j rpheq lxenaiwcga](https://user-images.githubusercontent.com/31695433/39460257-a70366d8-4d34-11e8-842d-0a1cda3eabfc.png)


问题解决了，我我总感觉你这个 包  用 npm install 安装 有毒 -_-||  

不管是 用 nmp 安装 npm install --save hexo-helper-live2d
还是说  用 npm install  安装 模型  他都会 把我上面图片里的 那两个文件夹 删除 没错 是直接删除了 -_-||

然后 在文件  package-lock.json 中 （后面两张 黑图 我用 vs 比较的）把那两个文件夹的  加载内容 也删除了    -_-||    

这就是 原因   你把删除的  全部 copy 回去  他就能找到 lunr 了  2d娘 也能加载 出来了  

具体原理 我还不知道  但解决 办法就这个了  (*^▽^*)

**Comment by EYHN** [comment]
使用 [yarn](https://yarnpkg.com/lang/en/) 可能会解决这个问题
