### ISSUE TITLE
模型大小可以根据页面大小进行自适应吗？

### ISSUE THREAD

**Issue by Latias94** [EYHN/hexo-helper-live2d#111]
# Issue

### Expected behavior 预期行为
不同的屏幕大小下，博客两侧的空白空间大小也不一样，17寸屏幕看博客效果不错，但是13寸屏幕看博客时，模型就会和正文重叠，能不能提供一种模型自适应的方法呢？根据窗口大小改模型大小之类的，或者页面宽度小于一个值的时候隐藏模型。
### Actual behavior 实际行为
![](https://ws1.sinaimg.cn/large/006tNc79gy1frcy6wkbf9j30jm0oytkk.jpg)
### Steps to reproduce the behavior 复现步骤
[博客](http://frankorz.com/) 页面宽度缩小至模型与文本重叠。
- [ ] I have alreday read instructions in [CONTRIBUTING](./CONTRIBUTING.md).
  我已仔细阅读[CONTRIBUTING](./CONTRIBUTING.md)中的相关内容。

> Change the `[ ]` into `[x]` to show your acceptance.
将 `[ ]` 变为 `[x]` 来表示你接受了这些问题。

@EYHN @xiazeyu

**Comment by xiazeyu** [comment]
@EYHN
我曾经有过这个提案
然后被他否决了...我在考虑给config.height增加一个5%的之类的允许值

**Comment by Latias94** [comment]
还有比较迷的就是我设置了移动端不显示，iPhone的确没显示了，但是iPad上看看板娘就出现了。
```
mobile:
  show: false
  scale: 0.5
```

**Comment by xiazeyu** [comment]
@Latias94
iPad被认为不算手机...

**Comment by Latias94** [comment]
@xiazeyu 好吧..希望有解决自适应的办法

**Comment by xiazeyu** [comment]
@Latias94

看看这样的解决方案如何

> Migrated to https://github.com/xiazeyu/live2d-widget.js/issues/19

**Comment by Latias94** [comment]
@xiazeyu 挺好的啊，做完了 at 下😀

**Comment by xiazeyu** [comment]
@Latias94 自己follow...
