### ISSUE TITLE
haru模型/01和/02子文件价中json文件为空

### ISSUE THREAD

**Issue by BeautyYuYanli** [EYHN/hexo-helper-live2d#112]
# Issue

## Description
npm包的haru模型/01和/02子文件价中json文件为空.希望能修改
### Steps to reproduce the behavior 复现步骤

- [ ] I have alreday read instructions in [CONTRIBUTING](./CONTRIBUTING.md).
  我已仔细阅读[CONTRIBUTING](./CONTRIBUTING.md)中的相关内容。

> Change the `[ ]` into `[x]` to show your acceptance.
将 `[ ]` 变为 `[x]` 来表示你接受了这些问题。

@EYHN @xiazeyu

**Comment by xiazeyu** [comment]
Migrated to https://github.com/xiazeyu/live2d-widget-models/issues/1
