### ISSUE TITLE
在主题的 `_config.yml` 文件中的配置项无法生效

### ISSUE THREAD

**Issue by Mrcxt** [EYHN/hexo-helper-live2d#114]
### plugin version 插件版本

hexo-helper-live2d: 3.0.3

在主题的 `_config.yml` 文件中的配置项貌似无法生效呐。 只有在网站的 `_config.yml` 文件中添加配置才会生效，求解

**Comment by xiazeyu** [comment]
@Mrcxt
https://github.com/EYHN/hexo-helper-live2d/blob/master/index.js#L37
如果网站的配置文件里已经有live2d配置组了, 主题里的有话也不会生效。请确认一下..
我们是更推荐使用网站配置文件的。

**Comment by Mrcxt** [comment]
我测试了几次，即使网站配置文件里不写live2d的配置，只在主题里写，也是不生效的。不知是不是我个人原因。

不过确实是写在网站配置文件里面要好。只是因为想在自己的主题里写好，让别人用的时候不需要太多的配置，所以才想写到主题配置里面

**Comment by xuanzebi** [comment]
为什么我这个还自带live2d 想去掉。。或者改改大小  求解
https://xuanzebi.github.io

**Comment by Mrcxt** [comment]
@xuanzebi 
如果不想使用，直接移除npm依赖就可以了。如果想配置，可以参照文档

**Comment by xiazeyu** [comment]
@Mrcxt 你的主题是
https://github.com/Mrcxt/xiabibi-cactus
吗?我可以帮你看看。

**Comment by Mrcxt** [comment]
@xiazeyu 是哒！

**Comment by xiazeyu** [comment]
@Mrcxt emmm
我想了一下，因为hexo安装主题是不通过npm的，也就是说直接把hexo-helper-live2d加入依赖并没有什么用，还需要让用户手动安装
然后试了一下，hexo-helper-live2d在`after_render`前无法读取hexo.theme.config.live2d，甚至连hexo.theme.config也是undefined

总之好像是我们读取theme设置的时间不对...@EYHN 您当时代码是怎么想的...

**Comment by Mrcxt** [comment]
@xiazeyu 
总之是这个样子了。貌似也确实没有写在主题配置文件里面的必要，

**Comment by xiazeyu** [comment]
Migrated to https://github.com/EYHN/hexo-helper-live2d/issues/116
