### ISSUE TITLE
换了model,不起作用

### ISSUE THREAD

**Issue by jerryc127** [EYHN/hexo-helper-live2d#119]
按着步骤
npm install --save hexo-helper-live2d

然后在Hexo的 _config.yml 文件添加了 

live2d:
  enable: true
  scriptFrom: local
  pluginRootPath: live2dw/
  pluginJsPath: lib/
  pluginModelPath: assets/
  model:
    use: live2d-widget-model-wanko
  display:
    position: right
    width: 150
    height: 300
  mobile:
    show: true

但是不起作用

然后在主题的 _config.yml 文件添加，可以显示宠物，但是显示的是shizuku这只（我设置的是wanko）
然后试着设置了其他的宠物，依旧是显示shizuku这只

hexo 和 next都是最新版

我的网站： jerryc.me

希望能帮我解决问题。。

**Comment by jerryc127** [comment]
已解決

**Comment by xiazeyu** [comment]
@jerryc127 建议您分享一下解决方法，以备后人查阅，谢谢
