### ISSUE TITLE
增加可以隐藏在边框的设置把

### ISSUE THREAD

**Issue by ElderJames** [EYHN/hexo-helper-live2d#12]
在手机端浏览，会挡住的

**Comment by EYHN** [comment]
我会考虑增加移动端不显示的功能的

**Comment by LanJD** [comment]
这个我已经解决了，加个行代码，当手机端浏览时，隐藏掉就可以了

**Comment by ElderJames** [comment]
判断一下，如果是移动端就不加载模型

**Comment by BBBob** [comment]
@LanJD 请问您是在哪具体加了什么代码呢？

**Comment by LanJD** [comment]
我本身不是很懂js和css，也就是自己试着添加，不过效果是可以在手机段访问的时候因此的，我的才折腾好搭建的博客lanjd.top
具体是如果你用的是next主题，themes\next\source\css\_custom中的custom.styl中添加代码
#live2dcanvas {
        +mobile() {
        display: none;
      }
}
差不多就可以隐藏了

**Comment by BBBob** [comment]
@LanJD 好的，谢谢～

**Comment by BBBob** [comment]
@EYHN 您好，我使用了一下next分支，有对话框显示出来，但是不知道如何在移动端隐藏。使用了LanJD的方法，可以隐藏模型，但是对话框还在。我对js也不是很熟悉。不知您可否在next分支中更新一下readme文档？

**Comment by EYHN** [comment]
@BBBob  我不鼓励使用next分支，next分支是正在开发的版本。next分支的提交应该会在近期并入master分支

**Comment by BBBob** [comment]
@EYHN 谢谢提醒～ 其实并没有实际使用next分支，只是对未来功能进行预览测试～

**Comment by CaptainYukinoshitaHachiman** [comment]
同样需求在手机端隐藏(´▽｀)

**Comment by newdee** [comment]
我觉得手机上隐藏比较好，手机上看起来像素太低

**Comment by xiazeyu** [comment]
@EYHN 我有一个想法，不知道能否实现，就是在手机端增加一个透明度的选项，当点击Live2D 角色或者是角色的某个部分时增加透明度
还有一个问题，能否做到每次hexo g 时只生成所用模型？感觉现在一生成所有模型都会被带到.git_deploy里面

**Comment by EYHN** [comment]
@xiazeyu 透明度可以通过css的opacity属性实现

**Comment by xiazeyu** [comment]
@EYHN 我再去试试，以前好像试过，但是因为用的是canvas所以好像会失效。
