### ISSUE TITLE
How to use live2d without Hexo? | 如何在Hexo外使用live2d?

### ISSUE THREAD

**Issue by OmmyZhang** [EYHN/hexo-helper-live2d#121]
I try to directly  use ``loadlive2d(...)``  but it seems that I can't find the right js

我的网站并不是使用Hexo搭建的,想使用live2d。 根据某篇文章的写法在直接在html中加入``<canvas ...></canvas>``和``<script>loadlive2d(...);</script>``, 但好像找不到loadlive2d是在哪个js里定义的,也不确定这种搞法对不对，想请教一下作者

**Comment by xiazeyu** [comment]
@OmmyZhang
See https://github.com/EYHN/hexo-helper-live2d/issues/6

**Comment by OmmyZhang** [comment]
@xiazeyu thx!

**Comment by xiazeyu** [comment]
Solved.
Same with https://github.com/EYHN/hexo-helper-live2d/issues/81
