### ISSUE TITLE
i  can  not     uninstall  it  completely

### ISSUE THREAD

**Issue by rs-v** [EYHN/hexo-helper-live2d#125]
@EYHN @xiazeyu

**Comment by EYHN** [comment]
Open terminal and run command
```
npm remove --save hexo-helper-live2d
```
Remove the configuration about live2d in `_config.yml`

**Comment by rs-v** [comment]
ok  i am sure  i can  remove it  bb

**Comment by EYHN** [comment]
I'm closing this but if you still have questions, we can reopen this.
