### ISSUE TITLE
Display two models at the same time

### ISSUE THREAD

**Issue by zyf722** [EYHN/hexo-helper-live2d#126]
**你的新功能与某一个问题有关吗?**
helper-live2d是否可以同时显示两个看板娘？

**你的方案是**
-

**一些你考虑过的替代方案有**
-

**额外的信息**
-

**Comment by EYHN** [comment]
不可以
pr welcome.

**Comment by xiazeyu** [comment]
只能自己手动调用两次live2d-widget.
