### ISSUE TITLE
Chrome浏览器问题

### ISSUE THREAD

**Issue by LanJD** [EYHN/hexo-helper-live2d#13]
不知道什么问题，我的chrome浏览器显示不出来，safari浏览器正常显示，这是那里没设置好么？

**Comment by EYHN** [comment]
我无法复现这个问题，我开发和测试都是在chrome上进行的。
请你打开你chrome的开发者控制台，检查是否有错误提示

**Comment by LanJD** [comment]
你好lanjd.top这是我新搭建的博客，问题
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
script.js:1 Live2D 2.1.00_1
script.js:1 profile : Desktop
script.js:1   [PROFILE_NAME] = Desktop
script.js:1   [USE_ADJUST_TRANSLATION] = false
script.js:1   [USE_CACHED_POLYGON_IMAGE] = false
script.js:1   [EXPAND_W] = 2

**Comment by EYHN** [comment]
你好，我这里看到live2d是生效的哦。
请你用chrome打开链接: chrome://gpu/
检查webgl是否可用。
如果设备过老或驱动不支持，webgl不会被启用

**Comment by LanJD** [comment]
谢谢，确实是浏览器的问题，搞明白了，浏览器中
WebGL: Unavailable
WebGL2: Unavailable
