### ISSUE TITLE
支持script标签直接引入吗

### ISSUE THREAD

**Issue by ZhangMingZhao1** [EYHN/hexo-helper-live2d#131]
比如像next.js这样，
`<script color="255,0,0" opacity='0.7' count = ’200‘ src="https://cdn.bootcss.com/canvas-nest.js/1.0.1/canvas-nest.js"></script>`

这样就可以支持博客园等一些博客了

**Comment by journey-ad** [comment]
用这个项目 [xiazeyu/live2d-widget.js](https://github.com/xiazeyu/live2d-widget.js)

**Comment by xiazeyu** [comment]
https://github.com/xiazeyu/live2d-widget.js/tree/master?files=1

**Comment by xiazeyu** [comment]
@xuziang111
要不你 npm install再npm run _esdoc一下?..
因为老版本的文档已经不再支持了..
https://github.com/xiazeyu/live2d-widget.js/blob/master/src/index.js
这里边也有介绍

**Comment by xiazeyu** [comment]
https://github.com/xiazeyu/live2d-widget.js/blob/dev/README.md
