### ISSUE TITLE
关于自定义模型

### ISSUE THREAD

**Issue by xuziang111** [EYHN/hexo-helper-live2d#132]
![image](https://user-images.githubusercontent.com/26647360/48669316-0ab58200-eb3d-11e8-9f6a-05c9662d96fd.png)
![image](https://user-images.githubusercontent.com/26647360/48669321-15701700-eb3d-11e8-9e9e-c41771e1c693.png)
应该都是按设置的路径
但是最后报了个404
![image](https://user-images.githubusercontent.com/26647360/48669323-23be3300-eb3d-11e8-84e2-14b97ccd4135.png)

# Issue

- [x] I have alreday read instructions in [CONTRIBUTING](CONTRIBUTING.md).
  我已仔细阅读[CONTRIBUTING](CONTRIBUTING.md)中的相关内容。

- [x] I have alreday read instructions in [README](../README.md).
  我已仔细阅读[README](../README.md)中的相关内容。

> Change the `[ ]` into `[x]` to show my acceptance.
将 `[ ]` 变为 `[x]` 来表示我接受了这些问题。

@xiazeyu @EYHN

**Comment by xiazeyu** [comment]
看起来是没检测到.model.json..
能否打开debug标签看看控制台输出?
