### ISSUE TITLE
请问透明度设置的属性是什么

### ISSUE THREAD

**Issue by xiyuvi** [EYHN/hexo-helper-live2d#138]
**描述你的问题**
请问透明度设置的属性是什么

我尝试了在  display:李加入opacity: 0.7 但是不管用0.0请教一下应该怎么设置。
我直接在html网页修改opacity 为0.7是可以透明的

**Comment by EYHN** [comment]
react.opacity

live2d:
  enable: true
  react:
    opacity: 0.7
