### ISSUE TITLE
配置修改无效

### ISSUE THREAD

**Issue by BestOfAll** [EYHN/hexo-helper-live2d#139]
**描述你的问题**
请简明清晰地描述您所遇到的问题
根据
https://11.tt/posts/2018/how-to-play-with-live2d-on-hexo/
集成插件和预期不符，
一直显示，
![image](https://user-images.githubusercontent.com/19755937/56348933-0da2c480-61fa-11e9-811b-746faebbe314.png)
而且在右侧
但是我可以看到作者的小蝙蝠，说明我的电脑和浏览器是支持显示的
我将配置 debug 设置为了 true 不知道 如何去看 = =   ，
https://bestofall.github.io/

**环境信息(请务必填写下列信息)**
- 操作系统: [e.g. iOS 8.1, Windows 10] 
   Windows 10
- 浏览器 [e.g. Chrome 66, Safari 11.2]
   Chrome 71.0.3578.98
- hexo-helper-live2d: [e.g. 3.0.0]
  -- hexo-helper-live2d@3.1.1

**额外的信息**
请在此处描述其他的内容
![image](https://user-images.githubusercontent.com/19755937/56349522-4d1de080-61fb-11e9-9bbf-17959ec1c8c5.png)

我在根_config.yml中配置：
![image](https://user-images.githubusercontent.com/19755937/56350318-16e16080-61fd-11e9-8c65-0121ad02f554.png)

- [x] 我已仔细阅读[CONTRIBUTING](CONTRIBUTING.md)中的相关内容。

- [x] 我已仔细阅读[README](../README.md)中的相关内容。

> 将 `[ ]` 变为 `[x]` 来表示我接受了这些问题。

@EYHN @xiazeyu

**Comment by BestOfAll** [comment]
实际效果应该在左下角 出现猫才对

**Comment by EYHN** [comment]
请注意您配置文件的缩进
yaml使用缩进来表示对象之间的关系

**Comment by EYHN** [comment]
https://github.com/EYHN/hexo-helper-live2d/blob/master/README.zh-CN.md
参考这里的文档

**Comment by BestOfAll** [comment]
可以了  灰常感谢
