### ISSUE TITLE
feat: message system

### ISSUE THREAD

**Issue by yunruios** [EYHN/hexo-helper-live2d#14]
好像没实现对话互动的功能，还是我操作不对？说明文档一句话概况了，~

**Comment by EYHN** [comment]
对话互动的功能依然是 Todo 就是还没有做，如果有任何 idea，请告诉我

**Comment by ElderJames** [comment]
可以用接入ai来实现对话？？比如微软的bot framework

**Comment by EYHN** [comment]
非常不错的想法。现在困扰我的是如何设计对话框的样式，以适应不同的主题风格

**Comment by ElderJames** [comment]
先实现功能，样式可以给用户修改就好了

**Comment by EYHN** [comment]
![image](https://user-images.githubusercontent.com/13579374/28995976-7a81dfb0-7a29-11e7-8a7d-2a30e39d27ee.png)

**Comment by BBBob** [comment]
@EYHN 对话框点开后，是否有方法可以将其隐藏呢？我展开对话框之后不知道如何使其重新隐藏。

**Comment by EYHN** [comment]
@BBBob 谢谢您的建议，我确实应该实现一个隐藏的方法。

**Comment by ElderJames** [comment]
无意中看到一个博客，也有二次元看板，能聊天的
https://blog.sukitsuki.com/2016/06/12/OS-X-Rebuild-brew-link/
项目好像是：
https://github.com/Kamira/Web-UkagakaProj

**Comment by newdee** [comment]
@EYHN 那个gif图输入的啊啊啊好卡哇伊，，，我觉着这个加入对话应该不难，现在Python流行做微信聊天机器人了，找不到API接进来可以直接仿着做一个。样式可以学学Facebook的网页底栏对话框，因为在gif中的对话框来看，应该保留一句话比较好看。

**Comment by newdee** [comment]
感觉互动聊天还是用处不大，毕竟AI起步没多久。
不过现在感觉可以加入两个功能，一个是像那种时不时冒出几句名人名言的，比如接入[一言](http://hitokoto.cn/api)的API,像这样的[效果](https://myhloli.com/feed-a.html)
另一个就是接入天气预报的API，让宠物可以预报天气。

**Comment by xiazeyu** [comment]
我也是打算写一个自己的“每日一句”，正好看起来可以接入live2dhelper，有空了去试试。我的每日一句是json的

**Comment by newdee** [comment]
@xiazeyu 你试了没？
@EYHN  请问怎么把json文件接入live2d？

**Comment by xiazeyu** [comment]
@EYHN @newdee 正在一项项解决Issue，然后提交一个PR看看，还有种想法就是直接把模型list变成json什么的挂在blog里的某个位置，这样更改会方便很多，不过还在研究

**Comment by newdee** [comment]
@xiazeyu 不过直接改成json的话，应该没有动画了吧，不会响应鼠标了

**Comment by xiazeyu** [comment]
就是把models,弄成json格式的，还有想办法避免像原版一样一下传一大堆文件上服务器。
还有在考虑增加一个判断手机端然后自定义手机端设置的东西。

**Comment by newdee** [comment]
@xiazeyu 恩，其实在选择了模型之后应该就生成选择的模型就行了，但是每次都是生成所有的模型

**Comment by xiazeyu** [comment]
issue后来有点跑题了，现恢复原来关于互动实现的讨论

**Comment by xiazeyu** [comment]
我现在有个想法就是重新开几个package，然后开放html内容片段的API。我在做一个“每日一句的package”，互动的可能也可以这样

**Comment by xiazeyu** [comment]
Migrated to https://github.com/xiazeyu/live2d-widget.js/issues/18
