### ISSUE TITLE
安装live2d使我的站内搜索功能失效(insight.js)和点击爱心效果失效(clicklove.js)

### ISSUE THREAD

**Issue by Icecream-blue-sky** [EYHN/hexo-helper-live2d#154]
**描述你的问题**
我的博客是hexo icarus，在安装live2d之前，站内搜索insight正常工作，以及自己加入的一个点击爱心脚本也正常；但安装live2d后，insight功能莫名失效了，点击搜索框没有任何反应，鼠标点击的爱心效果也消失了。当然之前也碰到busuanzi和live2d矛盾的问题，我在想是不是同样的问题，这很令我困惑。

**复现步骤**
点击博客的搜索框，无任何反应；点击博客任意地方，无爱心效果出现，爱心效果按照https://angericky.github.io/2018/12/24/icarus%E4%B8%AA%E6%80%A7%E5%AE%9A%E5%88%B6/ 配置。浏览器调试报如下错：
![temp](https://user-images.githubusercontent.com/26771037/70677738-f6ee3800-1cca-11ea-8afc-0e7f9d058e8d.png)

出现问题的网站地址:https://zoutq.com/
**将 `log` 选项设置为 `true` 来显示完整的日志.**
`_config.yml` 中的配置:
`live2d:
  enable: true
  scriptFrom: local
  pluginRootPath: live2dw/
  pluginJsPath: lib/
  pluginModelPath: assets/
  tagMode: false
  debug: false
  model:
    use: live2d-widget-model-hijiki
  display:
    position: right
    width: 200
    height: 400
  mobile:
    show: true
  react:
    opacity: 0.7`

控制台输出:

1. 打开'...'
2. 双击'...'
3. 滑动到'...'
4. 发现截图中所示错误

**预期的行为**
预期效果应该同https://angericky.github.io/2018/12/24/icarus%E4%B8%AA%E6%80%A7%E5%AE%9A%E5%88%B6/一样，点击搜索框可以正常搜索；点击博客任意处，出现爱心效果。

**屏幕截图**
如果可能, 请添加一些屏幕截图来更好地描述你的问题

**环境信息(请务必填写下列信息)**
- 设备: [ PC]
- 操作系统: [Windows 10]
- 浏览器 [Chrome]
- hexo-helper-live2d: [3.1.1]
> 使用 `npm ls hexo-helper-live2d` 来获取当前插件版本.

**额外的信息**
请在此处描述其他的内容

- [x ] 我已仔细阅读[CONTRIBUTING](CONTRIBUTING.md)中的相关内容。

- [x ] 我已仔细阅读[README](../README.md)中的相关内容。

> 将 `[ ]` 变为 `[x]` 来表示我接受了这些问题。

@EYHN @xiazeyu

**Comment by Icecream-blue-sky** [comment]
version:
hexo 3.9.0

**Comment by EYHN** [comment]
显然你的hexo出现了一些问题

你的 clicklove.js 明显不完整
![image](https://user-images.githubusercontent.com/13579374/70795449-cac1dc80-1dda-11ea-85de-37e9e70f664a.png)

你的 main.js 结尾突然出现html标签
![image](https://user-images.githubusercontent.com/13579374/70795525-f6dd5d80-1dda-11ea-9d50-0036ecf76266.png)

hexo-helper-live2d 应该不会导致这个问题，你能不能上传一个能够复现这个bug的最小demo，我或许能给你解决这个问题

**Comment by Icecream-blue-sky** [comment]
> 显然你的hexo出现了一些问题
> 
> 你的 clicklove.js 明显不完整
> ![image](https://user-images.githubusercontent.com/13579374/70795449-cac1dc80-1dda-11ea-85de-37e9e70f664a.png)
> 
> 你的 main.js 结尾突然出现html标签
> ![image](https://user-images.githubusercontent.com/13579374/70795525-f6dd5d80-1dda-11ea-9d50-0036ecf76266.png)
> 
> hexo-helper-live2d 应该不会导致这个问题，你能不能上传一个能够复现这个bug的最小demo，我或许能帮你你解决这个问题

请问我能直接上传源代码，要复现这个bug的话，我又得重新都弄一遍（第四遍。。。）

**Comment by Icecream-blue-sky** [comment]
> 显然你的hexo出现了一些问题
> 
> 你的 clicklove.js 明显不完整
> ![image](https://user-images.githubusercontent.com/13579374/70795449-cac1dc80-1dda-11ea-85de-37e9e70f664a.png)
> 
> 你的 main.js 结尾突然出现html标签
> ![image](https://user-images.githubusercontent.com/13579374/70795525-f6dd5d80-1dda-11ea-9d50-0036ecf76266.png)
> 
> hexo-helper-live2d 应该不会导致这个问题，你能不能上传一个能够复现这个bug的最小demo，我或许能帮你你解决这个问题

这是我今天刚更新的我的博客全部的更改记录：https://zoutq.com/2019/12/18/hexo-icarus%E5%8D%9A%E5%AE%A2%E6%9B%B4%E6%94%B9%E8%AE%B0%E5%BD%95/，不知道对解决问题是否有什么帮助

**Comment by Icecream-blue-sky** [comment]
My problem has been solved by this——https://github.com/hexojs/hexo/issues/3989.It's not the problem of live2d.Forgive my fault.Hope to help someone like me.
