### ISSUE TITLE
Warning after install this script

### ISSUE THREAD

**Issue by newdee** [EYHN/hexo-helper-live2d#17]
After install this script, it always comes out  like this:
```
(node:9217) [DEP0061] DeprecationWarning: fs.SyncWriteStream is deprecated.

```

**Comment by EYHN** [comment]
This looks like `hexo-fs` is problem. https://github.com/hexojs/hexo-cli/issues/21
And it will not affect the use.

**Comment by xiazeyu** [comment]
#18 我借鉴hexo-prism-plugin的做法，建议将package.json中的hexo-fs升级到最新版本

**Comment by xiazeyu** [comment]
@EYHN 等待作者大大把我最近的pr更新到npm上应该就解决了

**Comment by newdee** [comment]
解决了，不是fs版本的问题，我用--debug看的是另一个插件的问题，abbrlink里的，后来把那行注释掉就好了。
