### ISSUE TITLE
模型可不可以设置左右移动啊

### ISSUE THREAD

**Issue by breakinferno** [EYHN/hexo-helper-live2d#21]
只有上下移动位置，求搞一波左右移动位置的配置吧

**Comment by breakinferno** [comment]
左右移动不能配置使用，只有在代码里手动覆盖感觉可以加一下

**Comment by newdee** [comment]
模型修改什么参数可以放在右侧呢？

**Comment by 1109585369** [comment]
怎么左右移动，默认位置挡住了部分按钮

**Comment by bfchengnuo** [comment]
@1109585369 
最简单的修改是在 `\node_modules\hexo-helper-live2d\index.js` 中的 71 行 right 改为 left

参考 #10
