### ISSUE TITLE
关于流行的动漫模型

### ISSUE THREAD

**Issue by newdee** [EYHN/hexo-helper-live2d#22]
可不可以新建几个比较流行的动漫模型，比如绅士们喜欢的Saber，蕾姆之类的～

**Comment by EYHN** [comment]
要有资源才行，自带的除了z16都是live2d官方放出的

newdee <notifications@github.com>于2017年9月15日周五 上午11:53写道：

**Comment by xiazeyu** [comment]
@EYHN 我自己找了些Live2D的模型，目录结构是这样子哒
```
│  cc_Rem.cfg
│  ico_rem.png
│  Rem.moc
│  Rem.model.json
│  Rem.physics.json
│
└─Rem.2048
        texture_00.png

```
还有这样子哒
```
│  cc_names_cocoa.cfg
│  cocoa.moc
│  cocoa.model.json
│  ico_cocoa.png
│
└─cocoa.2048
        texture_00.png
```
是直接丢到`node_modules\hexo-helper-live2d\assets`然后改`_config.yml`就好了吗？
还有缺少`*.physics.json`会有什么问题嘛？
谢谢

**Comment by EYHN** [comment]
要改这个https://github.com/EYHN/hexo-helper-live2d/blob/master/index.js#L8-L26

**Comment by xiazeyu** [comment]
谢谢了，那么那个Physic的json文件需要用到吗？

**Comment by EYHN** [comment]
应该会自动包含的。

**Comment by EYHN** [comment]
需要

**Comment by xiazeyu** [comment]
注意：以上部分内容不再有效。
最新版本用法请参照README
强烈建议将您的模型文件放在`live2d_models`文件夹下

Contents above isn't valid any more.
For the correct usage, please have a look at README.
It's highly recommend to put your model under the `live2d_models` folder.
