### ISSUE TITLE
关于加载速度的优化

### ISSUE THREAD

**Issue by newdee** [EYHN/hexo-helper-live2d#24]
这个宠物挺不错的，但是放在博客后感觉加载明显满了很多，我看了一下，时间有时候会很长，请问有没有什么可以加速的方案？
![screenshot from 2017-09-27 20-37-09](https://user-images.githubusercontent.com/12610440/30913791-00a9f712-a3c4-11e7-8268-73ce88cc514d.png)

**Comment by EYHN** [comment]
最简单的方式，你可以通过压缩 png 图片来降低大小

其他我再研究一下

>

**Comment by xiazeyu** [comment]
然而emmmmm, Live2D 模型好像都是moc文件呀

**Comment by xiazeyu** [comment]
好吧，我看错了，拖时间的的确是png文件。我用的插件可以压缩png。不过为什么我的模型好像png文件很少？

**Comment by xiazeyu** [comment]
分享一下我是使用的压缩插件
hexo-filter-cleanup

**Comment by xiazeyu** [comment]
最新版本已经对自带的assets进行了压缩。
