### ISSUE TITLE
关于首页的一个问题

### ISSUE THREAD

**Issue by newdee** [EYHN/hexo-helper-live2d#25]
博客主页一直有一个错误是关于live2d的index里的，不知道是不是启用了HTTPS的原因。
![Uploading Screenshot from 2017-09-30 01-38-30.png…]()

```
Get https://sp0.baidu.com/9_Q4simg2RQJ8t7jm9iCKT-xh_/s.gif?l=https://newdee.cf/ net::ERR_BLOCKED_BY_CLIENT
```

**Comment by EYHN** [comment]
？ 你是不是要传什么截图

**Comment by newdee** [comment]
显示不出来么?尴尬:smile: 我试着再上传一遍~
![这个](https://i.loli.net/2017/09/30/59cf391bf00dd.png)
(好像还是上传不了，提示 Something went really wrong, and we can't process that file. 所以就用图床外链啦)

**Comment by EYHN** [comment]
你说哪个页面？这看起来并不是live2d的问题

**Comment by xiazeyu** [comment]
@newdee 看起来是百度链接 主动推送的js有问题？

**Comment by newdee** [comment]
不好意思，好像是之前浏览器的问题，给定位在live2d里了，这个锅我帮你还给百度:smile:

**Comment by newdee** [comment]
fixed on #25
