### ISSUE TITLE
关于初次进入页面的Uncaught TypeError

### ISSUE THREAD

**Issue by newdee** [EYHN/hexo-helper-live2d#26]
有个小问题，每次浏览器第一次打开页面时，会有报错:
![image](https://user-images.githubusercontent.com/12610440/31655590-e67a44da-b35b-11e7-8188-98aacde09b52.png)
之后Reload页面，错误就消失。

**Comment by chanshiyucx** [comment]
不嫌麻烦的话，可以找到node_modules/hexo-helper-live2d/dist/bundle.js, 在第一个getDrawDataIndex之前加一句`if(this.live2DModel === null)return!1;`，就像下面，虽然不知道为什么，但之后没有报错了

![20171025110230](https://user-images.githubusercontent.com/22583039/31978548-9224adb6-b974-11e7-8089-d92eeaa15b88.png)

**Comment by newdee** [comment]
问题以及解决了，感谢@chanshiyucx提供帮助。具体方法是修改dist文件夹下的bundle.js，在第一个getDrawDataIndex(t)的前面一个function里加一个判断，
```
if(this.live2DModel === null)return!1;
```
顺便请求在源文件中修改，以及提供模型左右放置的设置。

**Comment by xiazeyu** [comment]
@newdee https://github.com/xiazeyu/hexo-helper-live2d/commit/4ad70f5db1e4f1cb150648ef179e5caaeacd807d
请帮我检查一下是否是这样修复的

**Comment by newdee** [comment]
@xiazeyu 对的，是这样修改。左右模型我是自己在本地修改的，等这里改完了再更新吧

**Comment by xiazeyu** [comment]
@newdee This problem have been fixed at my latest pr, so you can close this issue now.
