### ISSUE TITLE
新版本的问题

### ISSUE THREAD

**Issue by newdee** [EYHN/hexo-helper-live2d#33]
之前在本地解决了 #26 的问题，后来更新之后又出现了Uncaught TypeError:
![image](https://user-images.githubusercontent.com/12610440/32528123-30967428-c46c-11e7-952e-39cc1868bb51.png)
然后看了下，貌似还是一样的解决方式，，，因为好像没变。。

**Comment by xiazeyu** [comment]
@newdee
请问你是使用npm install的方法更新的吗？
最近不想npm上的版本跟进太快，所以目前npm是落后github3个commits的。
我会在npm更新之后@你，请届时在确认，谢谢。
如果你对这个问题很纠结，可以先clone使用github上的版本。

**Comment by xiazeyu** [comment]
https://github.com/EYHN/hexo-helper-live2d/commit/cb4468e18ada4e6d9374de6245b4d1b8016e9bd4
这个版本应该是彻底解决了的

**Comment by newdee** [comment]
@xiazeyu 
我用的npm，那等你先更新吧，谢谢

**Comment by xiazeyu** [comment]
@newdee 请更新npm查看问题是否解决，谢谢。
https://github.com/EYHN/hexo-helper-live2d/commit/f9f535e0e3fea2453b8f20d257ef7baa26250495

**Comment by newdee** [comment]
@xiazeyu 更新了，已经OK，谢谢
