### ISSUE TITLE
maupassant这个主题怎么安装？

### ISSUE THREAD

**Issue by zuosc** [EYHN/hexo-helper-live2d#34]
配置了没反应。

我看主题的文件是jade。。。 要怎么改呢

**Comment by xiazeyu** [comment]
@zuosc
嗯，没错的话，你可以试试在某个地方加一句`#{ live2d() }`
因为你主题的目录结构不是很清楚，你可以研究一下layout/_partial目录下的jade文件。

**Comment by zuosc** [comment]
@xiazeyu   我在footer.jade文件的末尾加上了#{ live2d() }。成功是成功了，但是出现了三个箭头。把布局搞的有点乱。

主题地址https://github.com/tufu9441/maupassant-hexo

**Comment by zuosc** [comment]
试了下  在另一个位置加，也会导致出现三个箭头。

似乎是没转义？

**Comment by xiazeyu** [comment]
三个箭头是什么意思..
我看swig脚本，应该只要调用live2d()直接获取html片段就可以了

**Comment by zuosc** [comment]
@xiazeyu 

http://blog.123456.cloud/

你拉倒最下面看下

**Comment by xiazeyu** [comment]
emmmmm,看起来是箭头匹配错误了？？？？
你试试顶头写？

**Comment by xiazeyu** [comment]
@zuosc我觉得应该你添加的位置不对。看源代码，live2d的代码重复了，而且没有被压缩..

**Comment by zuosc** [comment]
@xiazeyu   orz,这就无能为力了。  我是后端开发，，，，前端仅限于能看的水平 - -、

跪求大佬帮忙看看

**Comment by xiazeyu** [comment]
你试试改成!{live2d()}，然后加在after_footer.jade下面
http://m.blog.csdn.net/rcjjian/article/details/72814653

**Comment by zuosc** [comment]
@xiazeyu   

成功

谢啦！

**Comment by xiazeyu** [comment]
看他的说明和你的报错加空格应该就可以了
就是
```
!{live2d()}
```
变成
```
  !{live2d()}
```
你的情况应该和中文无关，不会因为中文报错。

然后你注意一下，我有计划在https://github.com/EYHN/hexo-helper-live2d/issues/36
中加入自动加载js的功能，这样就不需要修改主题文件了。如果成功的话，你还需要把这句语句移除掉Orz

（jade语法反人类）

**Comment by xiazeyu** [comment]
@zuosu 你可以继续尝试解决或者等待3.0版本发布（也可能会等很久 很久，就是...很久的很久）

目前的消息是3.0版本会有这方面的大更新，不需要再手动修改主题模板了

**Comment by zuosc** [comment]
@xiazeyu   哈哈哈  好吧。  

谢谢帮忙啦
