### ISSUE TITLE
不优雅的device.js引用

### ISSUE THREAD

**Issue by xiazeyu** [EYHN/hexo-helper-live2d#35]
按
https://segmentfault.com/a/1190000009478526
的方法创造dependency然后直接引用

**Comment by EYHN** [comment]
使用 webpack 打包在 bundle.js 中，减少请求

**Comment by xiazeyu** [comment]
@EYHN 嗯，我想如果是device加在bundle.js里的话，移动设备就要下载一个巨型js，而事实上这个巨型js并不会被加载

**Comment by EYHN** [comment]
webpack 可以异步加载模块，但代码会被分成2个文件。

其实我们并不需要device.js这么多功能。是否可以使用浏览器api做简单判断。

**Comment by xiazeyu** [comment]
嗯，我不知道你所说的浏览器API是不是这个意思
https://www.zhihu.com/question/21357506
我个人认为用device.js bug什么的可能会比较少，UA判断也更加精确，方便以后可能的细分设备优化。

用Webpack异步= =我觉得现在逻辑还算清晰，用异步和手动引用没什么差别，要说差别也可能只是代码美观度上Orz
