### ISSUE TITLE
feat: Import code in hexo-helper without modify template

### ISSUE THREAD

**Issue by xiazeyu** [EYHN/hexo-helper-live2d#36]
- [x] 自动将js代码加入html相应位置，免去手动修改模板的麻烦
- [x] https://hexo.io/api/filter.html
- [x] https://hexo.io/api/posts.html#Render
- [x] https://github.com/Troy-Yang/hexo-lazyload-image/blob/master/lib/addscripts.js
- [x] https://github.com/Troy-Yang/hexo-lazyload-image/blob/master/index.js
> 思路应该是 让hexo在ejs渲染结束，生成html后来调用js，然后再用js去prase html加代码片段

**Comment by EYHN** [comment]
`break change` 放在 3.0 吧

**Comment by xiazeyu** [comment]
然后导入的bundle.js需要?v=版本

**Comment by xiazeyu** [comment]
让hexo在ejs渲染结束，生成html后来调用js，然后再用js去prase html加代码片段可以吧

**Comment by xiazeyu** [comment]
enable option
