### ISSUE TITLE
Test Case 补全

### ISSUE THREAD

**Issue by xiazeyu** [EYHN/hexo-helper-live2d#38]
- [ ] Test Case 补全

**Comment by xiazeyu** [comment]
https://segmentfault.com/a/1190000002921481
http://cnodejs.org/topic/558df089ebf9c92d17e73358
https://coveralls.io/
https://travis-ci.org/
http://cnodejs.org/topic/57c68052b4a3bca66bbddbdd

**Comment by EYHN** [comment]
这个项目前端不好测，后端太少不用测，所以我觉得不用测试

**Comment by xiazeyu** [comment]
@EYHN 先把这个Issue搁置以下吧，加到了longTerm和3.0+里，等先把最近的Issues都解决了再研究。
