### ISSUE TITLE
例子在360阅览器中没效果

### ISSUE THREAD

**Issue by zlq4863947** [EYHN/hexo-helper-live2d#40]
### Expected behavior 预期行为
看到2D人物
### Actual behavior 实际行为
没看到
### Steps to reproduce the behavior 复现步骤
安装个360阅览器看看

只支持chrome吗

@EYHN @xiazeyu

**Comment by xiazeyu** [comment]
@zlq4863947 
应该是支持360浏览器的。
请将您的博客网址发过来，或者右键调试，如果有报错请复制粘贴
提供更多信息，这样才能诊断错误

**Comment by zlq4863947** [comment]
![1](https://user-images.githubusercontent.com/6490251/32837144-bcf57f8e-ca4f-11e7-9417-9ca9cc6eb871.png)
![2](https://user-images.githubusercontent.com/6490251/32837146-bf60337c-ca4f-11e7-9036-5385f4a6f254.png)
![3](https://user-images.githubusercontent.com/6490251/32837148-c0e1fcbc-ca4f-11e7-883e-c5c425180324.png)

**Comment by xiazeyu** [comment]
https://github.com/EYHN/hexo-helper-live2d/issues/13
尝试输入chrome://gpu/
再进入https://get.webgl.org/截图，谢谢

**Comment by zlq4863947** [comment]
搞了半天 还是不行 好像是360阅览器不支持webgl, chrome和safar都是好的 算了不折腾了

**Comment by xiazeyu** [comment]
你可以看一下#13，里面貌似也有人遇到了类似的问题。
你可以尝试升级一下浏览器版本。
https://get.webgl.org/
如果你的页面是这个样子的
![untitled](https://user-images.githubusercontent.com/10560038/32838988-c801d8de-ca4d-11e7-8097-7daccf14d905.png)
请继续折腾。

**Comment by xiazeyu** [comment]
@zlq4863947 若您确认是浏览器问题，与本插件无关，请关闭Issue，谢谢。

**Comment by xiazeyu** [comment]
http://doesmybrowsersupportwebgl.com/
https://get.webgl.org/
add these two links to document, so that users can check whether their browsers support WebGL.
