### ISSUE TITLE
feat: add support for idle and mtn

### ISSUE THREAD

**Issue by journey-ad** [EYHN/hexo-helper-live2d#43]
提取到的一些模型含有久置动作，想把这些动作利用起来。
例如鼠标停留或移出浏览器窗口指定时间后触发

另外现在未对鼠标点击做处理吗？我看 [main.js](https://github.com/EYHN/hexo-helper-live2d/blob/master/src/main.js#L349-L371) 里未处理 `mousedown` 和 `mouseup` 事件

@EYHN @xiazeyu

**Comment by xiazeyu** [comment]
https://github.com/EYHN/hexo-helper-live2d/blob/master/src/main.js#L369

**Comment by journey-ad** [comment]
@xiazeyu 
将`DEBUG_LOG`和`DEBUG_MOUSE_LOG`设置为`true`之后观察到每次移动鼠标都会触发点击事件；带有HIT_AREA的模型在目标区域移动鼠标会触发点击动作，点击鼠标反而无效
移动鼠标时的日志
```
onMouseDown device( x:17 y:34 ) view( x:-0.9735294112470001 y:1.3058823584578931) main.js:303
tapEvent view x:-0.9735294112470001 y:1.3058823584578931 LAppLive2DManager.js:109
```
根据[main.js#L363-L364](https://github.com/EYHN/hexo-helper-live2d/blob/master/src/main.js#L363-L364)来看，每次移动鼠标都会调用`modelTurnHead`方法，而`modelTurnHead`又会触发点击事件[main.js#L310](https://github.com/EYHN/hexo-helper-live2d/blob/master/src/main.js#L310)，[LAppLive2DManager.js#L105-L126](https://github.com/EYHN/hexo-helper-live2d/blob/master/src/LAppLive2DManager.js#L105-L126)
这是否为一个错误？

**Comment by EYHN** [comment]
正是如此设计的 因为这里的live2d拥有css属性 pointer-events: none; 不会收集到鼠标点击事件

**Comment by xiazeyu** [comment]
应该是一个错误。如果你有想法请提交代码，我过几天也会加入待办并修改。

**Comment by xiazeyu** [comment]
@EYHN，这个问题我想再看看别人都是怎么解决的。也许可以用js办法解决，增加layer的方式解决吧，或者别的什么方式解决吧。

**Comment by xiazeyu** [comment]
```js
this.models[i].startRandomMotion(cDefine.MOTION_GROUP_PINCH_IN,
      cDefine.PRIORITY_NORMAL);
this.models[i].startRandomMotion(cDefine.MOTION_GROUP_PINCH_OUT,
      cDefine.PRIORITY_NORMAL);
```

**Comment by xiazeyu** [comment]
- [ ] 将motion组所有的动作都使用起来
- [ ] 确认声音可以正常加载
#53

**Comment by xiazeyu** [comment]
- [ ] Improve MatrixStack

**Comment by xiazeyu** [comment]
https://developer.mozilla.org/zh-CN/docs/Web/Events

**Comment by xiazeyu** [comment]
Migrated to https://github.com/xiazeyu/live2d-widget.js/issues/14
