### ISSUE TITLE
feat: update to Cubism3 using pixiJs

### ISSUE THREAD

**Issue by xiazeyu** [EYHN/hexo-helper-live2d#50]
- [ ] Cubism3
- [ ] pixi
- [ ] 可能存在的模型兼容性问题

**Comment by EYHN** [comment]
pixi.min.js 414kb

**Comment by xiazeyu** [comment]
may create a new branch future.

**Comment by xiazeyu** [comment]
Migrated to https://github.com/xiazeyu/live2d-widget.js/issues/13
