### ISSUE TITLE
3.0 developing log

### ISSUE THREAD

**Issue by xiazeyu** [EYHN/hexo-helper-live2d#51]
- [x] 用js动态创造canvas
- [x] 内联style
- [x] 把参数都加到loadlive2d()的参数里
- [x] 把loadScript合并到device.min.js里
- [x] 简化代码
- [x] 修改cJs代码为单model
- [x] 分组settings
- [x] 最终把载入代码简化到一行
- [x] 能用js自动生成
- [x] 挂githubraw
- [x] 做一个通用代码（直接贴在wordpress或者什么奇怪的网页上就能直接用的那种）
- [x] webpack能不能用类似ejs，swig的模板功能，在相应位置添加js的hash？能否压缩html和其中的js？
- [x] 提醒用户升级的时候删除模板中的旧代码，更改_config.yml什么的？我想到可以把helper.generator()中的return替换成console.warn之类的。
- [x] 直接引入webpack编译完成的代码和js在线生成器
- [x] Webbrach
- [x] 调整 cJs function 顺序

http://www.jb51.net/article/78597.htm
http://blog.csdn.net/m0_37886429/article/details/69226386

**Comment by geyan666** [comment]
问下，那个设置的代码添加到哪里

**Comment by geyan666** [comment]
就是设置大小高度模型的那个

**Comment by xiazeyu** [comment]
@geyan666 _config.yml

**Comment by xiazeyu** [comment]
@EYHN
好的
1，div只是显示这是一个独立的元素这个意思吗？就是去掉了直接cnvas也没问题，但是加了更加规范？因为也没有利用div的任何特性= =
4，比较好奇为什么会未设置headPos...
是这种：loadlive2d("live2dcanvas", url) instead of loadlive2d("canvas", url, 0.5)这种意思吗？
6，可以的。我看live2d的官方repo也是这样用的到时候我做完部分工作再来开pages。

**Comment by xiazeyu** [comment]
Protect branches
Only merge the highest quality code. You can configure repositories to require status checks, reducing both human error and administrative overhead.

**Comment by xiazeyu** [comment]
https://help.github.com/articles/configuring-protected-branches/

**Comment by xiazeyu** [comment]
megra next to master Branch, and switch the working branch to next.

**Comment by xiazeyu** [comment]
README:
统一svg样式
# 相关项目


# Quick Start

``` html
<div id="app"></div>
<!-- 加载 cplayer 脚本 -->
<script src=".../cplayer.js"></script>
<script>
  let player = new cplayer({
    element: document.getElementById('app'),
    playlist: [
      {
        src: '歌曲资源链接...',
        poster: '封面链接...',
        name: '歌曲名称...',
        artist: '歌手名称...',
        lyric: '歌词...',
        sublyric: '副歌词，一般为翻译...',
        album: '专辑，唱片...'
      },
      {
        ...
      },
      ......
    ]
  })
</script>
```

## webpack

```
npm install cplayer --save
```

```
import cplayer from 'cplayer';

new cplayer({
  ...
})
```


# Option

|OPTION|default content|description|
|:-----|:-------------:|:----------|
|element|`document.body`|注入播放器的目标元素。|
|playlist|`[]`|播放列表。|
|zoomOutKana|`false`|日语优化，缩小显示歌词中的假名。|
|playmode|`listloop`|默认播放模式。|
|volume|`1`|默认音量|
|point|`0`|开始播放的歌曲索引。|
|showPlaylist|`false`|显示播放列表，而不是当前歌曲信息。|
|autoplay|`false`|自动播放（移动端不可用）。|
|width|`''`|播放器宽度。|
|size|`12px`|播放器尺寸。|
|style|`''`|附加的css样式。|
|showPlaylistButton|`'true'`|显示播放列表按钮|
|dropDownMenuMode|`'bottom'`|菜单（播放列表和歌曲信息）的显示模式， ‘bottom’ 底部、 'top' 顶部、 'none' 不显示|


<details><summary>我只需要一个封装好的 audio api，不想要 UI ？</summary><br>

`dist` 文件夹中有 `cplayer-noview.js` 是去 UI 版的 cplayer。

</details>

**Comment by xiazeyu** [comment]
http://blog.csdn.net/m0_37886429/article/details/69226386

**Comment by xiazeyu** [comment]
http://www.jb51.net/article/78597.htm

**Comment by xiazeyu** [comment]
no test case /sad

**Comment by xiazeyu** [comment]
All issues have divided into smaller ones, so that this issue is closed.
