### ISSUE TITLE
feat: custom HIT_AREA support

### ISSUE THREAD

**Issue by journey-ad** [EYHN/hexo-helper-live2d#52]
部分模型不带 HIT_AREA，是否可增加相应处理，使得通过`model.json`中提供的参数手动定义 HIT_AREA。
定义方式可使用矩形区域左上角和右下角两点坐标。
坐标可通过启用`DEBUG_MOUSE_LOG`得到，因此与此同时应能方便的修改`LAppDefine`

@EYHN @xiazeyu

**Comment by xiazeyu** [comment]
可以考虑，但是本人短期内实现还比较困难Orz
而且模型有没有Expression也是个问题

**Comment by xiazeyu** [comment]
added `debug.mouseFunc` and debug options in config to give the mouse position back.

**YOU SHOULD ONLY MODIFY THE .model.json FILE TO ADDED HIT_AREA, instead achieve it using this js.**
