### ISSUE TITLE
bug: poor motion reaction

### ISSUE THREAD

**Issue by caozihao** [EYHN/hexo-helper-live2d#53]
### Expected behavior 预期行为
拿shizuku 为例声音包里有15个文件，分为5个场景下的声音，但是无论我怎么点，都只有两种声音...特别是点击头部区域的时候，没有声音
### Actual behavior 实际行为
 只有两种声音
### Steps to reproduce the behavior 复现步骤
点击！点击！点击！

- [x] I have alreday read instructions in [CONTRIBUTING](./CONTRIBUTING.md). 
我已仔细阅读[CONTRIBUTING](./CONTRIBUTING.md)中的相关内容。

> Change the `[ ]` into `[x]` to show your acceptance.
将 `[ ]` 变为 `[x]` 来表示你接受了这些问题。

@EYHN @xiazeyu

**Comment by xiazeyu** [comment]
目前貌似挺多人反应模型啊，动作啊的问题的。
已经加入待办，不过实际处理可能还需要很长时间

**Comment by xiazeyu** [comment]
https://github.com/EYHN/hexo-helper-live2d/issues/43
类似问题
目前问题锁定在不是所有的motion都能被反馈
可能特定motion被重复了很多次。

**Comment by xiazeyu** [comment]
此issue已合并 #43
