### ISSUE TITLE
Can live2d be used on typecho?

### ISSUE THREAD

**Issue by dzy0302** [EYHN/hexo-helper-live2d#69]
### Steps to reproduce the behavior 复现步骤

@EYHN @xiazeyu

**Comment by EYHN** [comment]
#6

**Comment by dzy0302** [comment]
@EYHN 我按照上面的教程尝试添加代码在footer.php上，没有加载成功，Chrome提示Refused to execute script from 'https://raw.githubusercontent.com/EYHN/hexo-helper-live2d/master/dist/bundle.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.查了一下好像被拒绝访问了，请问是什么原因呢？

**Comment by dzy0302** [comment]
另外一个js地址打不开，404

**Comment by dzy0302** [comment]
试了几个方式都不行，貌似js不能这样引用，我的引用方法好像不对。。

**Comment by dzy0302** [comment]
/* 对应的 model.json 文件 */里面我尝试过填model名，相对路径，绝对路径都不行

**Comment by xiazeyu** [comment]
@dzy0302 

Typecho的使用方式不能按Hexo的方式使用，应该关注这个东西
https://github.com/xiazeyu/live2d-widget.js
这个是从本项目中单独分离出的，以后会上CDN，不用githubusercontent，这样MINE类型就不会错误了
另一个地址已失效，别管，等live2d-widget.js或#6的最新发布就行
model名需要绝对路径....估计是因为没有加载成功代码导致的无效。

**Comment by dzy0302** [comment]
@xiazeyu 非常感谢你的教程，已在typecho上成功加载
