### ISSUE TITLE
中文README文档404啦

### ISSUE THREAD

**Issue by Ultraliyue** [EYHN/hexo-helper-live2d#71]
https://github.com/EYHN/hexo-helper-live2d/blob/master/readme.zh-CN.md

开发者注意下。。。

**Comment by xiazeyu** [comment]
在dev分支中已修改，3.0版本更新时会合并修复。

**Comment by sanyucz** [comment]
@xiazeyu 请问下有没有支持jekyll的打算啊，或者说如果我用jekyll的话有没有办法也用上呢

**Comment by xiazeyu** [comment]
@sanyucz
有这个计划,但是..应该属于有生之年系列了吧
你可以先参阅下面这些Issue.
https://github.com/EYHN/hexo-helper-live2d/issues/81
https://github.com/EYHN/hexo-helper-live2d/issues/6
今后的除Hexo以外的使用将会基于
https://github.com/xiazeyu/live2d-widget.js
(正在进行)
