### ISSUE TITLE
Advice 

### ISSUE THREAD

**Issue by JERE-MIAH** [EYHN/hexo-helper-live2d#73]
希望作者帮帮我这个强迫症，NEXT主题默认设置在mist主题下没有任何问题，但在piscs主题下会挡住一些东西，可不可以给我个右下角piscs的准确设置数值lol

**Comment by xiazeyu** [comment]
你可以看看
horizontalOffset: 0 # The horizontal offset. default: 0
verticalOffset: -20 # The offset of the bottom. default: -20
还有..透明度设定
opacityDefault
现在就这些设置..希望能帮到你

**Comment by xiazeyu** [comment]
你好，这些是否解决你的问题？如已解决请关闭Issue，谢谢。

**Comment by JERE-MIAH** [comment]
谢谢，已解决请关闭

2018年1月19日 上午6:28，"Retomehere" <notifications@github.com>写道：
