### ISSUE TITLE
horizontalOffset参数失效

### ISSUE THREAD

**Issue by EstherStarry** [EYHN/hexo-helper-live2d#79]
### Expected behavior 预期行为
position默认true，为置右端，设成false则lived2d置左端。horizontalOffset参数是设置水平偏置的，position默认情况下，正值为向左偏移，负值为向右偏移。

### Actual behavior 实际行为
此时horizontalOffset失效，无论设置成水平偏置多少，位置都没有变化。

### Steps to reproduce the behavior 复现步骤
在hexo根_config.yml文件，将position置为false，再设置horizontalOffset参数，无论重新本地运行或重新部署，水平偏置都没有效果。

@EYHN @xiazeyu

**Comment by xiazeyu** [comment]
position仅能设置为
`left`或者`right`
而不是true和false
请检查是否解决问题，将在4.0加入设置检查
