### ISSUE TITLE
额，结是什么鬼?

### ISSUE THREAD

**Issue by chenhonzhou** [EYHN/hexo-helper-live2d#94]
emmmmmmm...
@EYHN @xiazeyu
![2018-03-17 17-02-56](https://user-images.githubusercontent.com/30407568/37553540-1727d686-2a05-11e8-8bd5-ae37bb1af0ac.png)

**Comment by xiazeyu** [comment]
...方便提供一下控制台日志和你的配置吗..
然后Ctrl+F5试试?

**Comment by xiazeyu** [comment]
或者提供这个页面也可以..

**Comment by journey-ad** [comment]
@xiazeyu 
遇到过几次这种情况，Windows和Linux都遇到过，Firefox和Chrome也都出现过，重启浏览器后正常
因为贴图都在一张图上，如果是贴图加载失败，不太可能出现一部分正常显示，另一部分异常的情况
两个浏览器发生同样的故障可能性也不是很大
所以我猜测可能是live2d的webGL SDK实现上有些问题，不过看不懂底层实现无从排解…

**Comment by xiazeyu** [comment]
@journey-ad 
emmmm这个花掉= =我是真的不知道是什么鬼...感觉像是资源加载的锅...
webGL方面...感觉稳定性也不会很差...应该不会出现这种难以复现的问题
还是希望如果成功复现，能收集一下Network等信息

**Comment by xiazeyu** [comment]
Lack of solid information.
信息不足。
